# Generated by Django 4.0.5 on 2022-07-06 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0002_rename_visit_lenght_visit_visit_length_visit_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='Day',
            field=models.DateField(),
        ),
    ]
