# Generated by Django 4.0.5 on 2022-07-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0004_alter_visit_visit_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='Visit_length',
            field=models.FloatField(choices=[(1.0, '1h'), (1.5, '1h 30min'), (2.0, '2h')], max_length=2, null=True),
        ),
    ]
