# Generated by Django 4.0.5 on 2022-07-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0005_alter_visit_visit_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='Combined_id',
            field=models.IntegerField(null=True),
        ),
    ]
