# Generated by Django 4.0.5 on 2022-07-07 16:00

import book_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0006_visit_combined_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='Day',
            field=models.DateField(validators=[book_app.validators.visit_day_validator]),
        ),
        migrations.AlterField(
            model_name='visit',
            name='Term',
            field=models.TimeField(null=True, validators=[book_app.validators.visit_term_validator]),
        ),
    ]
