# Generated by Django 4.0.5 on 2022-07-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0007_alter_visit_day_alter_visit_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='Combined_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
