# Generated by Django 4.0.5 on 2022-12-30 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0008_alter_visit_combined_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='Combined_id',
        ),
        migrations.AlterField(
            model_name='visit',
            name='Visit_length',
            field=models.FloatField(),
        ),
    ]
